#!/bin/bash

set -euo pipefail

if [[ -z "${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_ROLE_ARN:-}" ]]; then
  echo "🚨 Missing 'role-arn' plugin configuration"
  exit 1
fi

echo "--- :buildkite::key::aws: Requesting an OIDC token for AWS from buildkite"

BUILDKITE_OIDC_TOKEN="$(buildkite-agent oidc request-token --audience sts.amazonaws.com)"

echo "--- :buildkite::key::aws::check: AWS OIDC token retrieved"

echo "--- :aws: Assuming role using OIDC token"

echo "Role ARN: ${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_ROLE_ARN}"

if [[ -n "${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_REGION:-}" ]]; then
  echo "AWS Region: ${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_REGION}"
  AWS_CLI_REGION_OPT="--region ${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_REGION}"
else
  echo "No target AWS Region was defined"
fi

AWS_ASSUME_ROLE_CMD="\
  aws ${AWS_CLI_REGION_OPT:-} \
  sts assume-role-with-web-identity \
  --role-arn ${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_ROLE_ARN} \
  --role-session-name \
  ${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_ROLE_SESSION_NAME:-buildkite-job-${BUILDKITE_JOB_ID}} \
  --web-identity-token ${BUILDKITE_OIDC_TOKEN}"

RESPONSE=$($AWS_ASSUME_ROLE_CMD)

if [[ $? -ne 0 ]]; then
  echo "^^^ +++"
  echo "Failed to assume AWS role:"
  echo "${RESPONSE}"
  exit 1
fi

export AWS_ACCESS_KEY_ID="$(jq -r ".Credentials.AccessKeyId" <<<"${RESPONSE}")"
export AWS_SECRET_ACCESS_KEY="$(jq -r ".Credentials.SecretAccessKey" <<<"${RESPONSE}")"
export AWS_SESSION_TOKEN="$(jq -r ".Credentials.SessionToken" <<<"${RESPONSE}")"

echo "Assumed role: $(jq -r .AssumedRoleUser.AssumedRoleId <<<"${RESPONSE}")"
