services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CI=true
      - LC_ALL=en_GB.UTF-8

  ci-cypress:
    build:
      context: .
      dockerfile: Dockerfile.ci-cypress
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - cypress_cache:/root/.cache/Cypress
    environment:
      - CI=true
      - LC_ALL=en_GB.UTF-8

volumes:
  node_modules:
  cypress_cache:
