@startuml

actor "Provisioning Service" as UPS
participant "Channel Orchestrator" as CO

UPS ->> CO: Create chat user
activate CO
CO ->> CO: Finds flexFlowSid with ChannelType.WEB
CO ->> CO: If exists, then Creates new ChatUser
CO ->> CO: Else, throws error
deactivate CO
CO ->> UPS: User Created

@enduml
