# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2
  cypress: cypress-io/cypress@1
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node18.12.0-chrome103-ff107'

jobs:
  cleanUp:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - run:
          command: yarn add twilio --no-save
          name: Install Twilio client
      - run:
          command: |
            yarn e2eCleanupExistingTasks \
                accountSid=$TWILIO_ACCOUNT_SID \
                authToken=$TWILIO_AUTH_TOKEN \
          name: Cleanup existing tasks
  runUnitTests:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
          with-cache: true
      - run:
          command: yarn test:nowatch
          name: Run YARN tests
      - store_test_results:
          path: /coverage
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./coverage
  cypressTestsOnSauce:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - run:
          name: "skipping e2e"
          command: echo "skipping e2e until further notice"
  sonarqubeCloudScan:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - sonarcloud/scan
workflows:
  build:
    jobs:
      - cleanUp
      - runUnitTests:
          requires:
            - cleanUp
      - sonarqubeCloudScan:
          requires:
            - runUnitTests
          context: SonarCloud
          filters:
            branches:
              only:
                - flex-webchat-ui
                - /.*FLEXIN-\d+.*/

