version: "2.1"

orbs:
  node: circleci/node@5.1.0
  aws-ecr: circleci/aws-ecr@9.0
  aws-cli: circleci/aws-cli@3.1
  terraform-helper: anyvan/terraform-helper@1
  aws: anyvan/aws_auth_config@1
  deployments: anyvan/deployments@1
  aws-ecr-helper: anyvan/aws-ecr-helper@2
  aws-tunnel-helper: anyvan/aws-tunnel-helper@2
  anyvan_github_ssh_key: anyvan/ssh_key_github@1

parameters:
  region:
    default: eu-west-1
    type: string
  modules:
    default: v0.0.79
    type: string
  terraform_version:
    default: "1.9.5"
    type: string
  jira_ticket_number:
    type: string
    default: $(echo $CIRCLE_BRANCH | sed -ne 's/[A-Z]*-\([0-9]*\)-.*/\1/p')
  image_tag:
    type: string
    default: $CIRCLE_SHA1
  workflow:
    type: string
    default: "deploy_to_pr_env"
  app_name:
    type: string
    default: "twilio-webchat-widget"

executors:
  base:
    docker:
      - image: cimg/base:current

  node-docker:
    docker:
      - image: cimg/node:20.19.2
    resource_class: small

  iac-base:
    docker:
      - image: $AWS_ECR_CIRCLECI_IMAGES_REPOSITORY_HOST/base/iac-base:noble
        aws_auth:
          oidc_role_arn: arn:aws:iam::$HORIZONTAL_ACCOUNT:role/circleci_oidc_role

jobs:
  build-and-push:
    parameters:
      image:
        type: string
      project-root:
        type: string
      env:
        type: string
      repository:
        type: string
      entry:
        type: string
      dockerfile:
        type: string
    executor: node-docker
    steps:
      - checkout
      - attach_workspace:
            at: ~/
      - run:
          name: Ensure docker-credential-helper is installed
          command: |
            sudo apt update && sudo apt install amazon-ecr-credential-helper
      - setup_remote_docker:
          docker_layer_caching: false
          version: default
      - run:
          name: "Build and push image to ECR"
          command: |
            PROJECT_REPOSITORY_URL=$AWS_ECR_CIRCLECI_IMAGES_REPOSITORY_HOST/<< pipeline.parameters.app_name >>
            PROJECT_REPOSITORY_HOST=$AWS_ECR_CIRCLECI_IMAGES_REPOSITORY_HOST
            docker build -f << parameters.dockerfile >> -t "${PROJECT_REPOSITORY_URL}/<< parameters.image >>:${CIRCLE_SHA1}" .
            docker push "${PROJECT_REPOSITORY_URL}/<< parameters.image >>:${CIRCLE_SHA1}"
  tag_image:
    executor:
      name: aws-ecr/default
    parameters:
      additional_tag:
        type: string
      source_tag:
        type: string
        default: "$CIRCLE_SHA1"
    steps:
      - attach_workspace:
          at: ~/
      - anyvan_github_ssh_key/install_ssh_key
      - aws-ecr/tag_image:
          repo: "<< pipeline.parameters.app_name >>"
          source_tag: "<< parameters.source_tag >>"
          target_tag: "<< parameters.additional_tag >>"


workflows:
  # Default workflow - Deploy to PR Environment
  deploy_to_pr_env:
    when:
      and:
        - not:
            equal: ["main", << pipeline.git.branch >>]
        - not:
            equal: ["", << pipeline.parameters.jira_ticket_number >>]
    jobs:
      - aws/init: &aws_init
          name: "Log in to AWS"
          context: anyvan
          region: << pipeline.parameters.region >>
          account: PRODUCTION HORIZONTAL TEST1
          persist: .aws
      - aws-ecr-helper/create_aws_ecr: &create_ecr
          name: "Create AWS ECR repository"
          context: anyvan
          module_path: "iac/terraform/image_repository"
          app_name: << pipeline.parameters.app_name >>
          tf_version: << pipeline.parameters.terraform_version >>
          requires:
            - "Log in to AWS"
      - aws-ecr-helper/ecr_login: &ecr_login
          name: "Log in to AWS ECR"
          context: anyvan
          requires:
            - "Create AWS ECR repository"
      # Build Server Image for PR Environment
      - build-and-push:
          name: build_webchat_server_pr
          project-root: .
          entry: .
          repository: server
          image: twilio-webchat-server
          dockerfile: Dockerfile.server
          env: testing
          requires:
            - "Log in to AWS ECR"

      # Build Client Image for PR Environment
      - build-and-push:
          name: build_webchat_client_pr
          project-root: .
          entry: .
          repository: client
          image: twilio-webchat-client
          dockerfile: Dockerfile.client
          env: testing
          requires:
            - "Log in to AWS ECR"
      - hold_pr:
          type: approval
          requires:
            - build_webchat_client_pr
            - build_webchat_server_pr
      # Plan Terraform for PR Environment
      - terraform-helper/plan: &plan
          name: plan_webchat_widget_pr
          context:
            - anyvan
            - twilio-flex-stage
          workspace: testing-<< pipeline.parameters.app_name >>-<< pipeline.parameters.jira_ticket_number >>
          var: >-
            jira_ticket_number=<< pipeline.parameters.jira_ticket_number >>,
            server_container_image_url=$AWS_ECR_CIRCLECI_IMAGES_REPOSITORY_HOST/<< pipeline.parameters.app_name >>/twilio-webchat-server-<< pipeline.parameters.image_tag >>,
            client_container_image_url=$AWS_ECR_CIRCLECI_IMAGES_REPOSITORY_HOST/<< pipeline.parameters.app_name >>/twilio-webchat-client-<< pipeline.parameters.image_tag >>,
            git_sha=$CIRCLE_SHA1,
            terraform_version=<< pipeline.parameters.terraform_version >>
          var_file: env/testing.tfvars
          modules_branch: << pipeline.parameters.modules >>
          path: terraform/
          terraform_version: << pipeline.parameters.terraform_version >>
          requires:
            - hold_pr
            - hold_pr

      # Apply Terraform for PR Environment
      - terraform-helper/apply: &apply
          name: apply_webchat_widget_pr
          context: anyvan
          workspace: testing-<< pipeline.parameters.app_name >>-<< pipeline.parameters.jira_ticket_number >>
          modules_branch: << pipeline.parameters.modules >>
          path: terraform/
          terraform_version: << pipeline.parameters.terraform_version >>
          requires:
            - plan_webchat_widget_pr

  pull_request_closed:
    when:
      and:
        - equal: [pull_request_closed, << pipeline.parameters.workflow >>]
        - not:
            equal: [main, << pipeline.git.branch >>]
        - not:
            equal: ["", << pipeline.parameters.jira_ticket_number >>]
    jobs:
      - aws/init:
          *aws_init
      - terraform-helper/plan:
          <<: *plan
          name: "Plan destroy PR environment"
          env: branches
          destroy: true
          var_file: env/branches.tfvars
          workspace: << pipeline.parameters.app_name >>_branches<< pipeline.parameters.jira_ticket_number >>
          requires:
            - "Log in to AWS"
      - terraform-helper/apply:
          <<: *apply
          name: "Apply Destroy of PR environment"
          destroy: true
          workspace: << pipeline.parameters.app_name >>_branches<< pipeline.parameters.jira_ticket_number >>
          requires:
            - "Plan destroy PR environment"









