#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

while IFS='=' read -r name _ ; do
  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_SM_FILE_[0-9]+_SECRET_ID)$ ]] ; then
    itemVar=$(echo "${name}" | sed 's/_SECRET_ID$//')
    secretId=$(strip_quotes "${!name}")
    pathVar="${itemVar}_PATH"
    path=$(strip_quotes "${!pathVar}")
    echo "Reading ${secretId} from AWS SM into file ${path}"
    get_secret_value "${secretId}" 'allow-binary' > "${path}"
  fi
done < <(env | sort)
