name: build-and-deploy
on:
  push:
    branches:
      - main
      - staging
      - develop
jobs:
  build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - name: Set Node.js 16.x
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
  
        - name: Run install
          uses: borales/actions-yarn@v4
          with:
            cmd: install

        - name: Build production bundle
          uses: borales/actions-yarn@v4
          with:
            cmd: build    
          env:
            ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
            REACT_APP_SERVER_URL: ${{ vars.REACT_APP_SERVER_URL }}
            DOWNLOAD_TRANSCRIPT_ENABLED: ${{ vars.DOWNLOAD_TRANSCRIPT_ENABLED }}
            EMAIL_TRANSCRIPT_ENABLED: ${{ vars.EMAIL_TRANSCRIPT_ENABLED }}

        - name: Extract branch name
          shell: bash
          run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          id: extract_branch

        - name: Deploy
          uses: nerdzila/s3-deploy@v7
          with:
            folder: build
            bucket: ${{ vars.S3_BUCKET }}
            bucket-region: ${{ vars.S3_BUCKET_REGION }}
            dist-id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
            file-prefix: /${{ steps.extract_branch.outputs.branch }}/
            invalidation: /
            delete-removed: true
            no-cache: true
            private: false
            files-to-include: '{.*/**,**}'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
